apiVersion: v1
data:
  index.html: |
    Hello from NGINX in Sector-2

kind: ConfigMap
metadata:
  name: ngx-s2-cm
  namespace: sector-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-s2
  name: ngx-s2
  namespace: sector-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-s2
  template:
    metadata:
      labels:
        app: ngx-s2
    spec:
      containers:
      - image: nginx:1.21.6
        name: ngx-s2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol 
          mountPath: /usr/share/nginx/html
          readOnly: True
      volumes:
      - name: vol
        projected:
          sources: 
           - configMap:
               name: ngx-s2-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngx-s2
  name: ngx-s2-svc
  namespace: sector-2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngx-s2
  sessionAffinity: None
  type: ClusterIP
---
