apiVersion: v1
data:
  index.html: |
    Hello from NGINX in Sector-1

kind: ConfigMap
metadata:
  name: {{name}}-cm
  namespace: {{namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{name}}
  name: {{name}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - image: {{image}}
        name: {{name}}
        ports:
        - containerPort: {{port}}
        volumeMounts:
        - name: vol 
          mountPath: /usr/share/nginx/html
          readOnly: True
      volumes:
      - name: vol
        projected:
          sources: 
           - configMap:
               name: {{name}}-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{name}}
  name: {{name}}-svc
  namespace: {{namespace}}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{port}}
    protocol: TCP
    targetPort: {{port}}
  selector:
    app: {{name}}
  sessionAffinity: None
  type: ClusterIP
---
