apiVersion: v1
data:
  haproxy.cfg: |
    defaults
        mode http
        log global
        balance roundrobin
        timeout client 30s

    frontend f1
        bind *:80
        default_backend b1
   
    backend b1
        server ngx1 ngx-s1-svc.sector-1.svc:80
        server ngx2 ngx-s2-svc.sector-2.svc:80
        server ngx3 ngx-s3-svc.sector-3.svc:80

kind: ConfigMap
metadata:
  name: hprx-full-cm
  namespace: proxy-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hprx-full
  name: hprx-full
  namespace: proxy-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hprx-full
  template:
    metadata:
      labels:
        app: hprx-full
    spec:
      containers:
      - image: haproxy:2.2.23-alpine
        name: hprx-full
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol 
          mountPath: /usr/local/etc/haproxy
          readOnly: True
      volumes:
      - name: vol
        projected:
          sources: 
           - configMap:
               name: hprx-full-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hprx-full
  name: hprx-full-svc
  namespace: proxy-hub
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hprx-full
  sessionAffinity: None
  type: ClusterIP
---
