apiVersion: v1
data:
  haproxy.cfg: |
    defaults
        mode http
        log global
        balance roundrobin
        timeout client 30s

    frontend f1
        bind *:80
        default_backend b1
   
    backend b1
        server ngx 127.0.0.1:80

kind: ConfigMap
metadata:
  name: {{name}}-cm
  namespace: {{namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{name}}
  name: {{name}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - image: {{image}}
        name: {{name}}
        ports:
        - containerPort: {{port}}
        volumeMounts:
        - name: vol 
          mountPath: /usr/local/etc/haproxy
          readOnly: True
      volumes:
      - name: vol
        projected:
          sources: 
           - configMap:
               name: {{name}}-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{name}}
  name: {{name}}-svc
  namespace: {{namespace}}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{port}}
    protocol: TCP
    targetPort: {{port}}
  selector:
    app: {{name}}
  sessionAffinity: None
  type: ClusterIP
---
